##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /collectionbuilder-gh 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-gh

##########
# SITE SETTINGS
#
# title of site appears in banner
title: "Assassins Creed: Fact or Fiction"
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: By Andrew Airiss, Diego and Sabrina
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Assassin’s Creed: Fact or Fiction? Show Notes

Title: Assassin’s Creed: Fact or Fiction: Episode 1

Authors:

Andrew Wise, Sabrina Gill, Diego Regalado, Airiss Tsang

Description:

History has often been left to the books. But with recent technological advances, how can we expand the media that our society uses to learn? Video games are one such way. Join us in our topic of conversation today, Assassin’s Creed, which uses some historical elements to tell a story of an Assassin during the Third Crusade in the Holy Land. To expand on the accuracy of the game our authors hosted a guest, Dr. Thabit Abdullah, professor of Islamic and Middle Eastern histories at York University. Together we talk about whether or not Assassin’s Creed is a good example of video games being used for historical educational purposes. 

Acknowledgments:

We would like to thank York University’s Media Creation Lab Team, for guiding us through this process and allowing us to use their equipment.
We would also like to thank Kris Joseph for his assistance with the website.
And to our special guest Professor Thabit Abdullah, we would like to thank him for allowing us to interview him and providing us with background information. 

Guests:

Professor Thabit Abdullah

References:
The educational value of Assassin’s Creed. Curio. CBC News, 2018. https://curio-ca.ezproxy.library.yorku.ca/en/catalog/54f2d071-afa0-40d9-8152-3bf8e0b78c9a.  
Milligan, Markus. “The Real Assassin’s Creed.” HeritageDaily, January 7, 2023. https://www.heritagedaily.com/2022/06/the-real-assassins-creed/143870.  
Moss, Richard. “Assassin’s Creed: An Oral History.” Polygon, October 3, 2018. https://www.polygon.com/features/2018/10/3/17924770/assassins-creed-an-oral-history-patrice-desilets.  
Santana, Ricardo. “14: Christian and Muslim Mentalities during the Third Crusade in Acre, Damascus and Jerusalem, Represented in Assassin’s Creed.” issuu, December 5, 2022. https://issuu.com/theuniversityofwinchester/docs/mamg22_proceedings/s/17585385.  
Taher, Hassan. “Representation of History in Assassin’s Creed.” 2018. https://lup.lub.lu.se/luur/download?func=downloadFile&recordOId=9012747&fileOId=9012752.  
"
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Andrew, Airiss, diego and Sabrina

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: test_gh

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png



##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code. See docs/google.md
#
# Add your google-analytics-id to automatically add the embed code, e.g. "G-123XXXXXX"
# google-analytics-id:
# to populate a Google CSE add the id, e.g. "002151703305773322890:1pu3smhw1t8"
# google-cse-id: 

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
# compress CSS output
sass:
  style: compressed
